# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_install_all_ios_pods
  pod 'Flutter', :path => File.expand_path('Flutter', __dir__)

  # Adding iOS dependencies for Flutter packages
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'geolocator', '~> 10.0'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Firestore'
  pod 'Firebase/Crashlytics'
  pod 'FlutterPluginRegistrant'
  pod 'audioplayers', '~> 0.20.1'
  pod 'syncfusion_flutter_pdfviewer', '~> 20.4.50'
  pod 'lottie-ios'
  pod 'SDWebImage'
  pod 'qr_flutter'
  pod 'shared_preferences_ios'
  pod 'hyperpay', '~> 2.0'
end

target 'Runner' do
  use_frameworks!
  flutter_install_all_ios_pods

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
    end
  end
end
